DROP TABLE USERS IF EXISTS;
CREATE TABLE USERS(id integer generated by default as identity (start with 1),
                  userId varchar(255), name varchar(255), password varchar(255), primary key (id));

CREATE TABLE USERS_PASSWORD(userId integer, passwdId integer);

CREATE TABLE PASSWORD(id integer generated by default as identity (start with 1),
                      alias varchar(255), site varchar(255), userName varchar(255), password varchar(255), primary key (id));